---
title: DFT
---

Resources related to DFT will be added here. 

## Some text books on DFT:

- Richard M. Martin. Electronic Structure_ Basic Theory and Practical Methods, 2nd Edition-Cambridge University Press (2020)
- Richard M. Martin. Interacting Electrons_ Theory and Computational Approaches (2016)
- Feliciano Giustino. Materials Modelling using Density unctional Theory - Properties and Predictions-Oxford University Press (2014)
- David Sholl, Janice A Steckel. Density functional theory - A practical introduction-Wiley-Interscience (2009)
- Wolfram Koch, Max C. Holthausen. A Chemist's Guide to Density Functional Theory. Wiley-VCH (2001)
- Carsten Ullrich. Time-Dependent Density-Functional Theory_ Concepts and Applications-Oxford University Press (2012)

## Some Useful links:

- See youtube channels of QuantumNerd and PhysWhiz
- Parnab Das' website.
- Mattermodeling on stack exchange is a very useful resource

## Foundantional Texts for Deeper Understanding:
- Walter Kohn's papers. 

<!-- ## abc
project:
  type: book

XYZ 
book:
  title: "Introduction to Density Functional Theory"
  author: "Your Name"
  date: today
  chapters:
  
- index.qmd
- 1_introduction.qmd
- 2_theoretical_fundamentals.qmd
- 3_ks_equations.qmd
- 4_xc_functionals.qmd
- 5_scf_calculation.qmd
- 6_geometry_optimization.qmd
- 7_band_structure.qmd
- 8_dos_and_pdos.qmd
- 9_practical_examples.qmd
- references.qmd -->


## DFT Lectures

- [Self-consistent Field (SCF) Calculation](lectures/scf.qmd)

<!-- - [Kohn-Sham Equations](ks_equation.qmd) -->

<!-- bibliography: bibliography.bib
format:
  html:
    theme: cosmo
    toc: true
  pdf:
    documentclass: book -->
